 name: Check Java Version

   on:
     workflow_dispatch:  # 允许手动触发
     schedule:
       - cron: '0 0 * * *'  # 每天午夜运行一次（可选）

   jobs:
     check-java-version:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up JDK
           uses: actions/setup-java@v2
           with:
             java-version: '11'
             distribution: 'adopt'

         - name: Check Java version
           run: ./check_java_version.sh
